version: "3.7"

services:

  gateway:
    container_name: nasty_gateway
    build:
      context: ./gateway
    restart: always
    ports:
      - ${HTTP_PORT}:8080
    depends_on:
      - server
    networks:
      - nasty-dash

  server:
    container_name: nasty_server
    build:
      context: ./server
      target: prod
    environment:
      MYSQL_HOST: 'nasty_mysql'
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always
    depends_on:
      - mysql
    networks:
      - nasty-dash

  redis:
    container_name: nasty_redis
    image: redis:latest
    networks:
      - nasty-dash

  mysql:
    container_name: nasty_mysql
    build:
      context: ./mysql
    restart: always
    volumes:
      - mysql_datastore:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=127.0.0.1", "--user=${MYSQL_USERNAME}", "--password=${MYSQL_PASSWORD}", "--silent"]
      interval: 10s
      timeout: 10s
      start_period: 30s
    networks:
      - nasty-dash

networks:
  nasty-dash:
    name: nasty-dash
    driver: bridge

volumes:
  mysql_datastore:
