version: "3.7"

services:

  gateway:
    volumes:
      - ./client/src/public:/app/src/public:delegated
      - client_build:/app/src/public/build

  server:
    build:
      context: ./server
      target: dev
      args:
        - XDEBUG_ACTIVE=${XDEBUG_ACTIVE}
    volumes:
      - ./server/src:/app/src:delegated
      - nasty_server_vendor:/app/src/vendor

  client:
    container_name: nasty_client
    build:
      context: ./client
      target: dev
    volumes:
      - ./client/src:/app/src:delegated
      - client_build:/app/src/build
      - client_vendors:/app/src/node_modules
    networks:
      - nasty-dash

volumes:
  nasty_server_vendor:
  client_vendors:
  client_build:
